// Archivo generado por src/scripts/sync-catalogs-sat.ts — NO editar a mano.
// Fuente: phpcfdi/resources-sat-catalogs v10.15.20260821 (catálogos SAT 2026-01-15).
// Regenerar con: npm run catalogs:sync

/* eslint-disable */
/** c_ConfigAutotransporte — configuración vehicular del autotransporte. */
export const CONFIGURACIONES_AUTOTRANSPORTE = {
  "VL": { "texto": "Vehículo ligero de carga (2 llantas en el eje delantero y 2 llantas en el eje trasero)", "numero_de_ejes": "2", "numero_de_llantas": "4", "remolque": "0, 1" },
  "C2": { "texto": "Camión Unitario (2 llantas en el eje delantero y 4 llantas en el eje trasero)", "numero_de_ejes": "2", "numero_de_llantas": "6", "remolque": "0" },
  "C3": { "texto": "Camión Unitario (2 llantas en el eje delantero y 6 o 8 llantas en los dos ejes traseros)", "numero_de_ejes": "3", "numero_de_llantas": "8", "remolque": "0" },
  "C2R2": { "texto": "Camión-Remolque (6 llantas en el camión y 8 llantas en remolque)", "numero_de_ejes": "4", "numero_de_llantas": "14", "remolque": "1" },
  "C3R2": { "texto": "Camión-Remolque (10 llantas en el camión y 8 llantas en remolque)", "numero_de_ejes": "5", "numero_de_llantas": "18", "remolque": "1" },
  "C2R3": { "texto": "Camión-Remolque (6 llantas en el camión y 12 llantas en remolque)", "numero_de_ejes": "5", "numero_de_llantas": "18", "remolque": "1" },
  "C3R3": { "texto": "Camión-Remolque (10 llantas en el camión y 12 llantas en remolque)", "numero_de_ejes": "6", "numero_de_llantas": "22", "remolque": "1" },
  "T2S1": { "texto": "Tractocamión Articulado (6 llantas en el tractocamión, 4 llantas en el semirremolque)", "numero_de_ejes": "3", "numero_de_llantas": "10", "remolque": "1" },
  "T2S2": { "texto": "Tractocamión Articulado (6 llantas en el tractocamión, 8 llantas en el semirremolque)", "numero_de_ejes": "4", "numero_de_llantas": "14", "remolque": "1" },
  "T2S3": { "texto": "Tractocamión Articulado (6 llantas en el tractocamión, 12 llantas en el semirremolque)", "numero_de_ejes": "5", "numero_de_llantas": "18", "remolque": "1" },
  "T3S1": { "texto": "Tractocamión Articulado (10 llantas en el tractocamión, 4 llantas en el semirremolque)", "numero_de_ejes": "4", "numero_de_llantas": "14", "remolque": "1" },
  "T3S2": { "texto": "Tractocamión Articulado (10 llantas en el tractocamión, 8 llantas en el semirremolque)", "numero_de_ejes": "5", "numero_de_llantas": "18", "remolque": "1" },
  "T3S3": { "texto": "Tractocamión Articulado (10 llantas en el tractocamión, 12 llantas en el semirremolque)", "numero_de_ejes": "6", "numero_de_llantas": "22", "remolque": "1" },
  "T2S1R2": { "texto": "Tractocamión Semirremolque-Remolque (6 llantas en el tractocamión, 4 llantas en el semirremolque y 8 llantas en el remolque)", "numero_de_ejes": "5", "numero_de_llantas": "18", "remolque": "1" },
  "T2S2R2": { "texto": "Tractocamión Semirremolque-Remolque (6 llantas en el tractocamión, 8 llantas en el semirremolque y 8 llantas en el remolque)", "numero_de_ejes": "6", "numero_de_llantas": "22", "remolque": "1" },
  "T2S1R3": { "texto": "Tractocamión Semirremolque-Remolque (6 llantas en el tractocamión, 4 llantas en el semirremolque y 12 llantas en el remolque)", "numero_de_ejes": "6", "numero_de_llantas": "22", "remolque": "1" },
  "T3S1R2": { "texto": "Tractocamión Semirremolque-Remolque (10 llantas en el tractocamión, 4 llantas en el semirremolque y 8 llantas en el remolque)", "numero_de_ejes": "6", "numero_de_llantas": "22", "remolque": "1" },
  "T3S1R3": { "texto": "Tractocamión Semirremolque-Remolque (10 llantas en el tractocamión, 4 llantas en el semirremolque y 12 llantas en el remolque)", "numero_de_ejes": "7", "numero_de_llantas": "26", "remolque": "1" },
  "T3S2R2": { "texto": "Tractocamión Semirremolque-Remolque (10 llantas en el tractocamión, 8 llantas en el semirremolque y 8 llantas en el remolque)", "numero_de_ejes": "7", "numero_de_llantas": "26", "remolque": "1" },
  "T3S2R3": { "texto": "Tractocamión Semirremolque-Remolque (10 llantas en el tractocamión, 8 llantas en el semirremolque y 12 llantas en el remolque)", "numero_de_ejes": "8", "numero_de_llantas": "30", "remolque": "1" },
  "T3S2R4": { "texto": "Tractocamión Semirremolque-Remolque (10 llantas en el tractocamión, 8 llantas en el semirremolque y 16 llantas en el remolque)", "numero_de_ejes": "9", "numero_de_llantas": "34", "remolque": "1" },
  "T2S2S2": { "texto": "Tractocamión Semirremolque-Semirremolque (6 llantas en el tractocamión, 8 llantas en el semirremolque delantero y 8 llantas en el semirremolque trasero)", "numero_de_ejes": "6", "numero_de_llantas": "22", "remolque": "1" },
  "T3S2S2": { "texto": "Tractocamión Semirremolque-Semirremolque (10 llantas en el tractocamión, 8 llantas en el semirremolque delantero y 8 llantas en el semirremolque trasero)", "numero_de_ejes": "7", "numero_de_llantas": "26", "remolque": "1" },
  "T3S3S2": { "texto": "Tractocamión Semirremolque-Semirremolque (10 llantas en el tractocamión, 12 llantas en el semirremolque delantero y 8 llantas en el semirremolque trasero)", "numero_de_ejes": "8", "numero_de_llantas": "30", "remolque": "1" },
  "OTROEVGP": { "texto": "Especializado de carga Voluminosa y/o Gran Peso", "numero_de_ejes": "0", "numero_de_llantas": "0", "remolque": "0, 1" },
  "OTROSG": { "texto": "Servicio de Grúas", "numero_de_ejes": "0", "numero_de_llantas": "0", "remolque": "0" },
  "GPLUTA": { "texto": "Grúa de Pluma Tipo A", "numero_de_ejes": "0", "numero_de_llantas": "0", "remolque": "0" },
  "GPLUTB": { "texto": "Grúa de Pluma Tipo B", "numero_de_ejes": "0", "numero_de_llantas": "0", "remolque": "0" },
  "GPLUTC": { "texto": "Grúa de Pluma Tipo C", "numero_de_ejes": "0", "numero_de_llantas": "0", "remolque": "0" },
  "GPLUTD": { "texto": "Grúa de Pluma Tipo D", "numero_de_ejes": "0", "numero_de_llantas": "0", "remolque": "0" },
  "GPLATA": { "texto": "Grúa de Plataforma Tipo A", "numero_de_ejes": "0", "numero_de_llantas": "0", "remolque": "0" },
  "GPLATB": { "texto": "Grúa de Plataforma Tipo B", "numero_de_ejes": "0", "numero_de_llantas": "0", "remolque": "0" },
  "GPLATC": { "texto": "Grúa de Plataforma Tipo C", "numero_de_ejes": "0", "numero_de_llantas": "0", "remolque": "0" },
  "GPLATD": { "texto": "Grúa de Plataforma Tipo D", "numero_de_ejes": "0", "numero_de_llantas": "0", "remolque": "0" },
} as const;

export type ConfiguracionesAutotransporteClave = keyof typeof CONFIGURACIONES_AUTOTRANSPORTE;

/** c_TipoPermiso — tipo de permiso SCT del autotransporte. */
export const TIPOS_PERMISO_SCT = {
  "TPAF01": { "texto": "Autotransporte Federal de carga general.", "clave_transporte": "01" },
  "TPAF02": { "texto": "Transporte privado de carga.", "clave_transporte": "01" },
  "TPAF03": { "texto": "Autotransporte Federal de Carga Especializada de materiales y residuos peligrosos.", "clave_transporte": "01" },
  "TPAF04": { "texto": "Transporte de automóviles sin rodar en vehículo tipo góndola.", "clave_transporte": "01" },
  "TPAF05": { "texto": "Transporte de carga de gran peso y/o volumen de hasta 90 toneladas.", "clave_transporte": "01" },
  "TPAF06": { "texto": "Transporte de carga especializada de gran peso y/o volumen de más 90 toneladas.", "clave_transporte": "01" },
  "TPAF07": { "texto": "Transporte Privado de materiales y residuos peligrosos.", "clave_transporte": "01" },
  "TPAF08": { "texto": "Autotransporte internacional de carga de largo recorrido.", "clave_transporte": "01" },
  "TPAF09": { "texto": "Autotransporte internacional de carga especializada de materiales y residuos peligrosos de largo recorrido.", "clave_transporte": "01" },
  "TPAF10": { "texto": "Autotransporte Federal de Carga General cuyo ámbito de aplicación comprende la franja fronteriza con Estados Unidos.", "clave_transporte": "01" },
  "TPAF11": { "texto": "Autotransporte Federal de Carga Especializada cuyo ámbito de aplicación comprende la franja fronteriza con Estados Unidos.", "clave_transporte": "01" },
  "TPAF12": { "texto": "Servicio auxiliar de arrastre en las vías generales de comunicación.", "clave_transporte": "01" },
  "TPAF13": { "texto": "Servicio auxiliar de servicios de arrastre, arrastre y salvamento, y depósito de vehículos en las vías generales de comunicación.", "clave_transporte": "01" },
  "TPAF14": { "texto": "Servicio de paquetería y mensajería en las vías generales de comunicación.", "clave_transporte": "01" },
  "TPAF15": { "texto": "Transporte especial para el tránsito de grúas industriales con peso máximo de 90 toneladas.", "clave_transporte": "01" },
  "TPAF16": { "texto": "Servicio federal para empresas arrendadoras servicio público federal.", "clave_transporte": "01" },
  "TPAF17": { "texto": "Empresas trasladistas de vehículos nuevos.", "clave_transporte": "01" },
  "TPAF18": { "texto": "Empresas fabricantes o distribuidoras de vehículos nuevos.", "clave_transporte": "01" },
  "TPAF19": { "texto": "Autorización expresa para circular en los caminos y puentes de jurisdicción federal con configuraciones de tractocamión doblemente articulado.", "clave_transporte": "01" },
  "TPAF20": { "texto": "Autotransporte Federal de Carga Especializada de fondos y valores.", "clave_transporte": "01" },
  "TPTM01": { "texto": "Permiso temporal para navegación de cabotaje", "clave_transporte": "02" },
  "TPTA01": { "texto": "Concesión y/o autorización para el servicio regular nacional y/o internacional para empresas mexicanas", "clave_transporte": "03" },
  "TPTA02": { "texto": "Permiso para el servicio aéreo regular de empresas extranjeras", "clave_transporte": "03" },
  "TPTA03": { "texto": "Permiso para el servicio nacional e internacional no regular de fletamento", "clave_transporte": "03" },
  "TPTA04": { "texto": "Permiso para el servicio nacional e internacional no regular de taxi aéreo", "clave_transporte": "03" },
  "TPXX00": { "texto": "Permiso no contemplado en el catálogo.", "clave_transporte": "01,02,03" },
} as const;

export type TiposPermisoSctClave = keyof typeof TIPOS_PERMISO_SCT;

/** c_SubTipoRem — subtipo de remolque / semirremolque. */
export const TIPOS_REMOLQUE = {
  "CTR001": { "texto": "Caballete" },
  "CTR002": { "texto": "Caja" },
  "CTR003": { "texto": "Caja Abierta" },
  "CTR004": { "texto": "Caja Cerrada" },
  "CTR005": { "texto": "Caja De Recolección Con Cargador Frontal" },
  "CTR006": { "texto": "Caja Refrigerada" },
  "CTR007": { "texto": "Caja Seca" },
  "CTR008": { "texto": "Caja Transferencia" },
  "CTR009": { "texto": "Cama Baja o Cuello Ganso" },
  "CTR010": { "texto": "Chasis Portacontenedor" },
  "CTR011": { "texto": "Convencional De Chasis" },
  "CTR012": { "texto": "Equipo Especial" },
  "CTR013": { "texto": "Estacas" },
  "CTR014": { "texto": "Góndola Madrina" },
  "CTR015": { "texto": "Grúa Industrial" },
  "CTR016": { "texto": "Grúa" },
  "CTR017": { "texto": "Integral" },
  "CTR018": { "texto": "Jaula" },
  "CTR019": { "texto": "Media Redila" },
  "CTR020": { "texto": "Pallet o Celdillas" },
  "CTR021": { "texto": "Plataforma" },
  "CTR022": { "texto": "Plataforma Con Grúa" },
  "CTR023": { "texto": "Plataforma Encortinada" },
  "CTR024": { "texto": "Redilas" },
  "CTR025": { "texto": "Refrigerador" },
  "CTR026": { "texto": "Revolvedora" },
  "CTR027": { "texto": "Semicaja" },
  "CTR028": { "texto": "Tanque" },
  "CTR029": { "texto": "Tolva" },
  "CTR031": { "texto": "Volteo" },
  "CTR032": { "texto": "Volteo Desmontable" },
} as const;

export type TiposRemolqueClave = keyof typeof TIPOS_REMOLQUE;

/** c_FiguraTransporte — tipo de figura de transporte (operador, propietario, etc.). */
export const FIGURAS_TRANSPORTE = {
  "01": { "texto": "Operador" },
  "02": { "texto": "Propietario" },
  "03": { "texto": "Arrendador" },
  "04": { "texto": "Notificado" },
  "05": { "texto": "Integrante de Coordinados" },
} as const;

export type FigurasTransporteClave = keyof typeof FIGURAS_TRANSPORTE;

/** c_TipoEmbalaje — tipo de embalaje para material peligroso. */
export const TIPOS_EMBALAJE = {
  "1A1": { "texto": "Bidones (Tambores) de Acero 1 de tapa no desmontable" },
  "1A2": { "texto": "Bidones (Tambores) de Acero 1 de tapa desmontable" },
  "1B1": { "texto": "Bidones (Tambores) de Aluminio de tapa no desmontable" },
  "1B2": { "texto": "Bidones (Tambores) de Aluminio de tapa desmontable" },
  "1D": { "texto": "Bidones (Tambores) de Madera contrachapada" },
  "1G": { "texto": "Bidones (Tambores) de Cartón" },
  "1H1": { "texto": "Bidones (Tambores) de Plástico de tapa no desmontable" },
  "1H2": { "texto": "Bidones (Tambores) de Plástico de tapa desmontable" },
  "1N1": { "texto": "Bidones (Tambores) de Metal que no sea acero ni aluminio de tapa no desmontable" },
  "1N2": { "texto": "Bidones (Tambores) de Metal que no sea acero ni aluminio de tapa desmontable" },
  "3A1": { "texto": "Jerricanes (Porrones) de Acero de tapa no desmontable" },
  "3A2": { "texto": "Jerricanes (Porrones) de Acero de tapa desmontable" },
  "3B1": { "texto": "Jerricanes (Porrones) de Aluminio de tapa no desmontable" },
  "3B2": { "texto": "Jerricanes (Porrones) de Aluminio de tapa desmontable" },
  "3H1": { "texto": "Jerricanes (Porrones) de Plástico de tapa no desmontable" },
  "3H2": { "texto": "Jerricanes (Porrones) de Plástico de tapa desmontable" },
  "4A": { "texto": "Cajas de Acero" },
  "4B": { "texto": "Cajas de Aluminio" },
  "4C1": { "texto": "Cajas de Madera natural ordinaria" },
  "4C2": { "texto": "Cajas de Madera natural de paredes a prueba de polvos (estancas a los pulverulentos)" },
  "4D": { "texto": "Cajas de Madera contrachapada" },
  "4F": { "texto": "Cajas de Madera reconstituida" },
  "4G": { "texto": "Cajas de Cartón" },
  "4H1": { "texto": "Cajas de Plástico Expandido" },
  "4H2": { "texto": "Cajas de Plástico Rígido" },
  "5H1": { "texto": "Sacos (Bolsas) de Tejido de plástico sin forro ni revestimientos interiores" },
  "5H2": { "texto": "Sacos (Bolsas) de Tejido de plástico a prueba de polvos (estancos a los pulverulentos)" },
  "5H3": { "texto": "Sacos (Bolsas) de Tejido de plástico resistente al agua" },
  "5H4": { "texto": "Sacos (Bolsas) de Película de plástico" },
  "5L1": { "texto": "Sacos (Bolsas) de Tela sin forro ni revestimientos interiores" },
  "5L2": { "texto": "Sacos (Bolsas) de Tela a prueba de polvos (estancos a los pulverulentos)" },
  "5L3": { "texto": "Sacos (Bolsas) de Tela resistentes al agua" },
  "5M1": { "texto": "Sacos (Bolsas) de Papel de varias hojas" },
  "5M2": { "texto": "Sacos (Bolsas) de Papel de varias hojas, resistentes al agua" },
  "6HA1": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con bidón (tambor) de acero" },
  "6HA2": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con una jaula o caja de acero" },
  "6HB1": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con un bidón (tambor) exterior de aluminio" },
  "6HB2": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con una jaula o caja de aluminio" },
  "6HC": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con una caja de madera" },
  "6HD1": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con un bidón (tambor) de madera contrachapada" },
  "6HD2": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con una caja de madera contrachapada" },
  "6HG1": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con un bidón (tambor) de cartón" },
  "6HG2": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con una caja de cartón" },
  "6HH1": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con un bidón (tambor) de plástico" },
  "6HH2": { "texto": "Envases y embalajes compuestos de Recipiente de plástico, con caja de plástico rígido" },
  "6PA1": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con un bidón (tambor) de acero" },
  "6PA2": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con una jaula o una caja de acero" },
  "6PB1": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con un bidón (tambor) exterior de aluminio" },
  "6PB2": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con una jaula o una caja de aluminio" },
  "6PC": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con una caja de madera" },
  "6PD1": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con bidón (tambor) de madera contrachapada" },
  "6PD2": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con canasta de mimbre" },
  "6PG1": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con un bidón (tambor) de cartón" },
  "6PG2": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con una caja de cartón" },
  "6PH1": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con un envase y embalaje de plástico expandido" },
  "6PH2": { "texto": "Envases y embalajes compuestos de Recipiente de vidrio, porcelana o de gres, con un envase y embalaje de plástico rígido" },
  "7H1": { "texto": "Bultos de Plástico" },
  "7L1": { "texto": "Bultos de Tela" },
  "Z01": { "texto": "No aplica" },
} as const;

export type TiposEmbalajeClave = keyof typeof TIPOS_EMBALAJE;

/** c_TipoCarga — tipo de carga (general / especializada). */
export const TIPOS_CARGA = {
  "CGS": { "texto": "Carga General Suelta" },
  "CGC": { "texto": "Carga General Contenerizada" },
  "GMN": { "texto": "Gran Mineral" },
  "GAG": { "texto": "Granel Agrícola" },
  "OFL": { "texto": "Otros Fluidos" },
  "PYD": { "texto": "Petróleo y Derivados" },
} as const;

export type TiposCargaClave = keyof typeof TIPOS_CARGA;

/** c_FormaPago — forma de pago del CFDI. */
export const FORMAS_PAGO = {
  "01": { "texto": "Efectivo" },
  "02": { "texto": "Cheque nominativo" },
  "03": { "texto": "Transferencia electrónica de fondos" },
  "04": { "texto": "Tarjeta de crédito" },
  "05": { "texto": "Monedero electrónico" },
  "06": { "texto": "Dinero electrónico" },
  "08": { "texto": "Vales de despensa" },
  "12": { "texto": "Dación en pago" },
  "13": { "texto": "Pago por subrogación" },
  "14": { "texto": "Pago por consignación" },
  "15": { "texto": "Condonación" },
  "17": { "texto": "Compensación" },
  "23": { "texto": "Novación" },
  "24": { "texto": "Confusión" },
  "25": { "texto": "Remisión de deuda" },
  "26": { "texto": "Prescripción o caducidad" },
  "27": { "texto": "A satisfacción del acreedor" },
  "28": { "texto": "Tarjeta de débito" },
  "29": { "texto": "Tarjeta de servicios" },
  "30": { "texto": "Aplicación de anticipos" },
  "31": { "texto": "Intermediario pagos" },
  "99": { "texto": "Por definir" },
} as const;

export type FormasPagoClave = keyof typeof FORMAS_PAGO;

/** c_MetodoPago — método de pago (PUE / PPD). */
export const METODOS_PAGO = {
  "PUE": { "texto": "Pago en una sola exhibición" },
  "PPD": { "texto": "Pago en parcialidades o diferido" },
} as const;

export type MetodosPagoClave = keyof typeof METODOS_PAGO;

/** c_Pais — países (ISO 3166-1 alpha-3 del SAT). */
export const PAISES = {
  "AFG": { "texto": "Afganistán", "patron_codigo_postal": "" },
  "ALA": { "texto": "Islas Åland", "patron_codigo_postal": "" },
  "ALB": { "texto": "Albania", "patron_codigo_postal": "" },
  "DEU": { "texto": "Alemania", "patron_codigo_postal": "" },
  "AND": { "texto": "Andorra", "patron_codigo_postal": "" },
  "AGO": { "texto": "Angola", "patron_codigo_postal": "" },
  "AIA": { "texto": "Anguila", "patron_codigo_postal": "" },
  "ATA": { "texto": "Antártida", "patron_codigo_postal": "" },
  "ATG": { "texto": "Antigua y Barbuda", "patron_codigo_postal": "" },
  "SAU": { "texto": "Arabia Saudita", "patron_codigo_postal": "" },
  "DZA": { "texto": "Argelia", "patron_codigo_postal": "" },
  "ARG": { "texto": "Argentina", "patron_codigo_postal": "" },
  "ARM": { "texto": "Armenia", "patron_codigo_postal": "" },
  "ABW": { "texto": "Aruba", "patron_codigo_postal": "" },
  "AUS": { "texto": "Australia", "patron_codigo_postal": "" },
  "AUT": { "texto": "Austria", "patron_codigo_postal": "" },
  "AZE": { "texto": "Azerbaiyán", "patron_codigo_postal": "" },
  "BHS": { "texto": "Bahamas (las)", "patron_codigo_postal": "" },
  "BGD": { "texto": "Bangladés", "patron_codigo_postal": "" },
  "BRB": { "texto": "Barbados", "patron_codigo_postal": "" },
  "BHR": { "texto": "Baréin", "patron_codigo_postal": "" },
  "BEL": { "texto": "Bélgica", "patron_codigo_postal": "" },
  "BLZ": { "texto": "Belice", "patron_codigo_postal": "" },
  "BEN": { "texto": "Benín", "patron_codigo_postal": "" },
  "BMU": { "texto": "Bermudas", "patron_codigo_postal": "" },
  "BLR": { "texto": "Bielorrusia", "patron_codigo_postal": "" },
  "MMR": { "texto": "Myanmar", "patron_codigo_postal": "" },
  "BOL": { "texto": "Bolivia, Estado Plurinacional de", "patron_codigo_postal": "" },
  "BIH": { "texto": "Bosnia y Herzegovina", "patron_codigo_postal": "" },
  "BWA": { "texto": "Botsuana", "patron_codigo_postal": "" },
  "BRA": { "texto": "Brasil", "patron_codigo_postal": "" },
  "BRN": { "texto": "Brunéi Darussalam", "patron_codigo_postal": "" },
  "BGR": { "texto": "Bulgaria", "patron_codigo_postal": "" },
  "BFA": { "texto": "Burkina Faso", "patron_codigo_postal": "" },
  "BDI": { "texto": "Burundi", "patron_codigo_postal": "" },
  "BTN": { "texto": "Bután", "patron_codigo_postal": "" },
  "CPV": { "texto": "Cabo Verde", "patron_codigo_postal": "" },
  "KHM": { "texto": "Camboya", "patron_codigo_postal": "" },
  "CMR": { "texto": "Camerún", "patron_codigo_postal": "" },
  "CAN": { "texto": "Canadá", "patron_codigo_postal": "[A-Z][0-9][A-Z] [0-9][A-Z][0-9]" },
  "QAT": { "texto": "Catar", "patron_codigo_postal": "" },
  "BES": { "texto": "Bonaire, San Eustaquio y Saba", "patron_codigo_postal": "" },
  "TCD": { "texto": "Chad", "patron_codigo_postal": "" },
  "CHL": { "texto": "Chile", "patron_codigo_postal": "" },
  "CHN": { "texto": "China", "patron_codigo_postal": "" },
  "CYP": { "texto": "Chipre", "patron_codigo_postal": "" },
  "COL": { "texto": "Colombia", "patron_codigo_postal": "" },
  "COM": { "texto": "Comoras", "patron_codigo_postal": "" },
  "PRK": { "texto": "Corea (la República Democrática Popular de)", "patron_codigo_postal": "" },
  "KOR": { "texto": "Corea (la República de)", "patron_codigo_postal": "" },
  "CIV": { "texto": "Côte d'Ivoire", "patron_codigo_postal": "" },
  "CRI": { "texto": "Costa Rica", "patron_codigo_postal": "" },
  "HRV": { "texto": "Croacia", "patron_codigo_postal": "" },
  "CUB": { "texto": "Cuba", "patron_codigo_postal": "" },
  "CUW": { "texto": "Curaçao", "patron_codigo_postal": "" },
  "DNK": { "texto": "Dinamarca", "patron_codigo_postal": "" },
  "DMA": { "texto": "Dominica", "patron_codigo_postal": "" },
  "ECU": { "texto": "Ecuador", "patron_codigo_postal": "" },
  "EGY": { "texto": "Egipto", "patron_codigo_postal": "" },
  "SLV": { "texto": "El Salvador", "patron_codigo_postal": "" },
  "ARE": { "texto": "Emiratos Árabes Unidos (Los)", "patron_codigo_postal": "" },
  "ERI": { "texto": "Eritrea", "patron_codigo_postal": "" },
  "SVK": { "texto": "Eslovaquia", "patron_codigo_postal": "" },
  "SVN": { "texto": "Eslovenia", "patron_codigo_postal": "" },
  "ESP": { "texto": "España", "patron_codigo_postal": "" },
  "USA": { "texto": "Estados Unidos (los)", "patron_codigo_postal": "[0-9]{5}(-[0-9]{4})?" },
  "EST": { "texto": "Estonia", "patron_codigo_postal": "" },
  "ETH": { "texto": "Etiopía", "patron_codigo_postal": "" },
  "PHL": { "texto": "Filipinas (las)", "patron_codigo_postal": "" },
  "FIN": { "texto": "Finlandia", "patron_codigo_postal": "" },
  "FJI": { "texto": "Fiyi", "patron_codigo_postal": "" },
  "FRA": { "texto": "Francia", "patron_codigo_postal": "" },
  "GAB": { "texto": "Gabón", "patron_codigo_postal": "" },
  "GMB": { "texto": "Gambia (La)", "patron_codigo_postal": "" },
  "GEO": { "texto": "Georgia", "patron_codigo_postal": "" },
  "GHA": { "texto": "Ghana", "patron_codigo_postal": "" },
  "GIB": { "texto": "Gibraltar", "patron_codigo_postal": "" },
  "GRD": { "texto": "Granada", "patron_codigo_postal": "" },
  "GRC": { "texto": "Grecia", "patron_codigo_postal": "" },
  "GRL": { "texto": "Groenlandia", "patron_codigo_postal": "" },
  "GLP": { "texto": "Guadalupe", "patron_codigo_postal": "" },
  "GUM": { "texto": "Guam", "patron_codigo_postal": "" },
  "GTM": { "texto": "Guatemala", "patron_codigo_postal": "" },
  "GUF": { "texto": "Guayana Francesa", "patron_codigo_postal": "" },
  "GGY": { "texto": "Guernsey", "patron_codigo_postal": "" },
  "GIN": { "texto": "Guinea", "patron_codigo_postal": "" },
  "GNB": { "texto": "Guinea-Bisáu", "patron_codigo_postal": "" },
  "GNQ": { "texto": "Guinea Ecuatorial", "patron_codigo_postal": "" },
  "GUY": { "texto": "Guyana", "patron_codigo_postal": "" },
  "HTI": { "texto": "Haití", "patron_codigo_postal": "" },
  "HND": { "texto": "Honduras", "patron_codigo_postal": "" },
  "HKG": { "texto": "Hong Kong", "patron_codigo_postal": "" },
  "HUN": { "texto": "Hungría", "patron_codigo_postal": "" },
  "IND": { "texto": "India", "patron_codigo_postal": "" },
  "IDN": { "texto": "Indonesia", "patron_codigo_postal": "" },
  "IRQ": { "texto": "Irak", "patron_codigo_postal": "" },
  "IRN": { "texto": "Irán (la República Islámica de)", "patron_codigo_postal": "" },
  "IRL": { "texto": "Irlanda", "patron_codigo_postal": "" },
  "BVT": { "texto": "Isla Bouvet", "patron_codigo_postal": "" },
  "IMN": { "texto": "Isla de Man", "patron_codigo_postal": "" },
  "CXR": { "texto": "Isla de Navidad", "patron_codigo_postal": "" },
  "NFK": { "texto": "Isla Norfolk", "patron_codigo_postal": "" },
  "ISL": { "texto": "Islandia", "patron_codigo_postal": "" },
  "CYM": { "texto": "Islas Caimán (las)", "patron_codigo_postal": "" },
  "CCK": { "texto": "Islas Cocos (Keeling)", "patron_codigo_postal": "" },
  "COK": { "texto": "Islas Cook (las)", "patron_codigo_postal": "" },
  "FRO": { "texto": "Islas Feroe (las)", "patron_codigo_postal": "" },
  "SGS": { "texto": "Georgia del sur y las islas sandwich del sur", "patron_codigo_postal": "" },
  "HMD": { "texto": "Isla Heard e Islas McDonald", "patron_codigo_postal": "" },
  "FLK": { "texto": "Islas Malvinas [Falkland] (las)", "patron_codigo_postal": "" },
  "MNP": { "texto": "Islas Marianas del Norte (las)", "patron_codigo_postal": "" },
  "MHL": { "texto": "Islas Marshall (las)", "patron_codigo_postal": "" },
  "PCN": { "texto": "Pitcairn", "patron_codigo_postal": "" },
  "SLB": { "texto": "Islas Salomón (las)", "patron_codigo_postal": "" },
  "TCA": { "texto": "Islas Turcas y Caicos (las)", "patron_codigo_postal": "" },
  "UMI": { "texto": "Islas de Ultramar Menores de Estados Unidos (las)", "patron_codigo_postal": "" },
  "VGB": { "texto": "Islas Vírgenes (Británicas)", "patron_codigo_postal": "" },
  "VIR": { "texto": "Islas Vírgenes (EE.UU.)", "patron_codigo_postal": "" },
  "ISR": { "texto": "Israel", "patron_codigo_postal": "" },
  "ITA": { "texto": "Italia", "patron_codigo_postal": "" },
  "JAM": { "texto": "Jamaica", "patron_codigo_postal": "" },
  "JPN": { "texto": "Japón", "patron_codigo_postal": "" },
  "JEY": { "texto": "Jersey", "patron_codigo_postal": "" },
  "JOR": { "texto": "Jordania", "patron_codigo_postal": "" },
  "KAZ": { "texto": "Kazajistán", "patron_codigo_postal": "" },
  "KEN": { "texto": "Kenia", "patron_codigo_postal": "" },
  "KGZ": { "texto": "Kirguistán", "patron_codigo_postal": "" },
  "KIR": { "texto": "Kiribati", "patron_codigo_postal": "" },
  "KWT": { "texto": "Kuwait", "patron_codigo_postal": "" },
  "LAO": { "texto": "Lao, (la) República Democrática Popular", "patron_codigo_postal": "" },
  "LSO": { "texto": "Lesoto", "patron_codigo_postal": "" },
  "LVA": { "texto": "Letonia", "patron_codigo_postal": "" },
  "LBN": { "texto": "Líbano", "patron_codigo_postal": "" },
  "LBR": { "texto": "Liberia", "patron_codigo_postal": "" },
  "LBY": { "texto": "Libia", "patron_codigo_postal": "" },
  "LIE": { "texto": "Liechtenstein", "patron_codigo_postal": "" },
  "LTU": { "texto": "Lituania", "patron_codigo_postal": "" },
  "LUX": { "texto": "Luxemburgo", "patron_codigo_postal": "" },
  "MAC": { "texto": "Macao", "patron_codigo_postal": "" },
  "MDG": { "texto": "Madagascar", "patron_codigo_postal": "" },
  "MYS": { "texto": "Malasia", "patron_codigo_postal": "" },
  "MWI": { "texto": "Malaui", "patron_codigo_postal": "" },
  "MDV": { "texto": "Maldivas", "patron_codigo_postal": "" },
  "MLI": { "texto": "Malí", "patron_codigo_postal": "" },
  "MLT": { "texto": "Malta", "patron_codigo_postal": "" },
  "MAR": { "texto": "Marruecos", "patron_codigo_postal": "" },
  "MTQ": { "texto": "Martinica", "patron_codigo_postal": "" },
  "MUS": { "texto": "Mauricio", "patron_codigo_postal": "" },
  "MRT": { "texto": "Mauritania", "patron_codigo_postal": "" },
  "MYT": { "texto": "Mayotte", "patron_codigo_postal": "" },
  "MEX": { "texto": "México", "patron_codigo_postal": "[0-9]{5}" },
  "FSM": { "texto": "Micronesia (los Estados Federados de)", "patron_codigo_postal": "" },
  "MDA": { "texto": "Moldavia (la República de)", "patron_codigo_postal": "" },
  "MCO": { "texto": "Mónaco", "patron_codigo_postal": "" },
  "MNG": { "texto": "Mongolia", "patron_codigo_postal": "" },
  "MNE": { "texto": "Montenegro", "patron_codigo_postal": "" },
  "MSR": { "texto": "Montserrat", "patron_codigo_postal": "" },
  "MOZ": { "texto": "Mozambique", "patron_codigo_postal": "" },
  "NAM": { "texto": "Namibia", "patron_codigo_postal": "" },
  "NRU": { "texto": "Nauru", "patron_codigo_postal": "" },
  "NPL": { "texto": "Nepal", "patron_codigo_postal": "" },
  "NIC": { "texto": "Nicaragua", "patron_codigo_postal": "" },
  "NER": { "texto": "Níger (el)", "patron_codigo_postal": "" },
  "NGA": { "texto": "Nigeria", "patron_codigo_postal": "" },
  "NIU": { "texto": "Niue", "patron_codigo_postal": "" },
  "NOR": { "texto": "Noruega", "patron_codigo_postal": "" },
  "NCL": { "texto": "Nueva Caledonia", "patron_codigo_postal": "" },
  "NZL": { "texto": "Nueva Zelanda", "patron_codigo_postal": "" },
  "OMN": { "texto": "Omán", "patron_codigo_postal": "" },
  "NLD": { "texto": "Países Bajos (los)", "patron_codigo_postal": "" },
  "PAK": { "texto": "Pakistán", "patron_codigo_postal": "" },
  "PLW": { "texto": "Palaos", "patron_codigo_postal": "" },
  "PSE": { "texto": "Palestina, Estado de", "patron_codigo_postal": "" },
  "PAN": { "texto": "Panamá", "patron_codigo_postal": "" },
  "PNG": { "texto": "Papúa Nueva Guinea", "patron_codigo_postal": "" },
  "PRY": { "texto": "Paraguay", "patron_codigo_postal": "" },
  "PER": { "texto": "Perú", "patron_codigo_postal": "" },
  "PYF": { "texto": "Polinesia Francesa", "patron_codigo_postal": "" },
  "POL": { "texto": "Polonia", "patron_codigo_postal": "" },
  "PRT": { "texto": "Portugal", "patron_codigo_postal": "" },
  "PRI": { "texto": "Puerto Rico", "patron_codigo_postal": "" },
  "GBR": { "texto": "Reino Unido (el)", "patron_codigo_postal": "" },
  "CAF": { "texto": "República Centroafricana (la)", "patron_codigo_postal": "" },
  "CZE": { "texto": "República Checa (la)", "patron_codigo_postal": "" },
  "MKD": { "texto": "Macedonia (la antigua República Yugoslava de)", "patron_codigo_postal": "" },
  "COG": { "texto": "Congo", "patron_codigo_postal": "" },
  "COD": { "texto": "Congo (la República Democrática del)", "patron_codigo_postal": "" },
  "DOM": { "texto": "República Dominicana (la)", "patron_codigo_postal": "" },
  "REU": { "texto": "Reunión", "patron_codigo_postal": "" },
  "RWA": { "texto": "Ruanda", "patron_codigo_postal": "" },
  "ROU": { "texto": "Rumania", "patron_codigo_postal": "" },
  "RUS": { "texto": "Rusia, (la) Federación de", "patron_codigo_postal": "" },
  "ESH": { "texto": "Sahara Occidental", "patron_codigo_postal": "" },
  "WSM": { "texto": "Samoa", "patron_codigo_postal": "" },
  "ASM": { "texto": "Samoa Americana", "patron_codigo_postal": "" },
  "BLM": { "texto": "San Bartolomé", "patron_codigo_postal": "" },
  "KNA": { "texto": "San Cristóbal y Nieves", "patron_codigo_postal": "" },
  "SMR": { "texto": "San Marino", "patron_codigo_postal": "" },
  "MAF": { "texto": "San Martín (parte francesa)", "patron_codigo_postal": "" },
  "SPM": { "texto": "San Pedro y Miquelón", "patron_codigo_postal": "" },
  "VCT": { "texto": "San Vicente y las Granadinas", "patron_codigo_postal": "" },
  "SHN": { "texto": "Santa Helena, Ascensión y Tristán de Acuña", "patron_codigo_postal": "" },
  "LCA": { "texto": "Santa Lucía", "patron_codigo_postal": "" },
  "STP": { "texto": "Santo Tomé y Príncipe", "patron_codigo_postal": "" },
  "SEN": { "texto": "Senegal", "patron_codigo_postal": "" },
  "SRB": { "texto": "Serbia", "patron_codigo_postal": "" },
  "SYC": { "texto": "Seychelles", "patron_codigo_postal": "" },
  "SLE": { "texto": "Sierra leona", "patron_codigo_postal": "" },
  "SGP": { "texto": "Singapur", "patron_codigo_postal": "" },
  "SXM": { "texto": "Sint Maarten (parte holandesa)", "patron_codigo_postal": "" },
  "SYR": { "texto": "Siria, (la) República Árabe", "patron_codigo_postal": "" },
  "SOM": { "texto": "Somalia", "patron_codigo_postal": "" },
  "LKA": { "texto": "Sri Lanka", "patron_codigo_postal": "" },
  "SWZ": { "texto": "Suazilandia", "patron_codigo_postal": "" },
  "ZAF": { "texto": "Sudáfrica", "patron_codigo_postal": "" },
  "SDN": { "texto": "Sudán (el)", "patron_codigo_postal": "" },
  "SSD": { "texto": "Sudán del Sur", "patron_codigo_postal": "" },
  "SWE": { "texto": "Suecia", "patron_codigo_postal": "" },
  "CHE": { "texto": "Suiza", "patron_codigo_postal": "" },
  "SUR": { "texto": "Surinam", "patron_codigo_postal": "" },
  "SJM": { "texto": "Svalbard y Jan Mayen", "patron_codigo_postal": "" },
  "THA": { "texto": "Tailandia", "patron_codigo_postal": "" },
  "TWN": { "texto": "Taiwán (Provincia de China)", "patron_codigo_postal": "" },
  "TZA": { "texto": "Tanzania, República Unida de", "patron_codigo_postal": "" },
  "TJK": { "texto": "Tayikistán", "patron_codigo_postal": "" },
  "IOT": { "texto": "Territorio Británico del Océano Índico (el)", "patron_codigo_postal": "" },
  "ATF": { "texto": "Territorios Australes Franceses (los)", "patron_codigo_postal": "" },
  "TLS": { "texto": "Timor-Leste", "patron_codigo_postal": "" },
  "TGO": { "texto": "Togo", "patron_codigo_postal": "" },
  "TKL": { "texto": "Tokelau", "patron_codigo_postal": "" },
  "TON": { "texto": "Tonga", "patron_codigo_postal": "" },
  "TTO": { "texto": "Trinidad y Tobago", "patron_codigo_postal": "" },
  "TUN": { "texto": "Túnez", "patron_codigo_postal": "" },
  "TKM": { "texto": "Turkmenistán", "patron_codigo_postal": "" },
  "TUR": { "texto": "Turquía", "patron_codigo_postal": "" },
  "TUV": { "texto": "Tuvalu", "patron_codigo_postal": "" },
  "UKR": { "texto": "Ucrania", "patron_codigo_postal": "" },
  "UGA": { "texto": "Uganda", "patron_codigo_postal": "" },
  "URY": { "texto": "Uruguay", "patron_codigo_postal": "" },
  "UZB": { "texto": "Uzbekistán", "patron_codigo_postal": "" },
  "VUT": { "texto": "Vanuatu", "patron_codigo_postal": "" },
  "VAT": { "texto": "Santa Sede[Estado de la Ciudad del Vaticano] (la)", "patron_codigo_postal": "" },
  "VEN": { "texto": "Venezuela, República Bolivariana de", "patron_codigo_postal": "" },
  "VNM": { "texto": "Viet Nam", "patron_codigo_postal": "" },
  "WLF": { "texto": "Wallis y Futuna", "patron_codigo_postal": "" },
  "YEM": { "texto": "Yemen", "patron_codigo_postal": "" },
  "DJI": { "texto": "Yibuti", "patron_codigo_postal": "" },
  "ZMB": { "texto": "Zambia", "patron_codigo_postal": "" },
  "ZWE": { "texto": "Zimbabue", "patron_codigo_postal": "" },
  "ZZZ": { "texto": "Países no declarados", "patron_codigo_postal": "" },
} as const;

export type PaisesClave = keyof typeof PAISES;
